using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
//using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraPivotGrid;

namespace DWM
{
    public partial class triates : DevExpress.XtraEditors.XtraForm
    {
        public triates()
        {
            InitializeComponent();
            controleHeader1.label_menu_btn = "الصفحة الرئيسية / الأقساط الشهرية";

            // This line of code is generated by Data Source Configuration Wizard
            view_traiteTableAdapter1.Fill(dataSetTraites1.view_traite);
        }

        private void triates_Load(object sender, EventArgs e)
        {
            try
            {
                gridControlEntr.DataSource = dataSetTraites1.Tables[0];
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }

        AjouterTraite TRform = new AjouterTraite();
        private void windowsUIButtonPanelMain_ButtonClick(object sender, DevExpress.XtraBars.Docking2010.ButtonEventArgs e)
        {
         
            if (e.Button.Properties.Tag == "Ajouter")
            {

                TRform.ShowDialog(this);

                view_traiteTableAdapter1.Fill(dataSetTraites1.view_traite);
                gridControlEntr.DataSource = dataSetTraites1.Tables[0];
            }
            else
            {
                gridViewEntr.Columns["nomcomp"].VisibleIndex = 4;
                gridViewEntr.Columns["MoisMTr"].VisibleIndex = 3;
                gridViewEntr.Columns["sta"].VisibleIndex = 2;
                gridViewEntr.Columns["DatePayerMTr"].VisibleIndex = 1;
                gridViewEntr.Columns["MontantMTr"].VisibleIndex = 0;

                gridControlEntr.ShowRibbonPrintPreview();

                gridViewEntr.Columns["nomcomp"].VisibleIndex = 0;
                gridViewEntr.Columns["MoisMTr"].VisibleIndex = 1;
                gridViewEntr.Columns["sta"].VisibleIndex = 2;
                gridViewEntr.Columns["DatePayerMTr"].VisibleIndex = 3;
                gridViewEntr.Columns["MontantMTr"].VisibleIndex = 4;
            }
        }
    }
}